services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - PG_DSN=${DATABASE_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - VITE_API_BASE_URL=/api
    restart: unless-stopped
