services:
  db:
    image: postgis/postgis:15-3.4
    container_name: sv_db_dev
    environment:
      POSTGRES_DB: sv
      POSTGRES_USER: sv
      POSTGRES_PASSWORD: sv
    ports:
      - "${PG_PORT:-55432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sv -d sv"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: sv_api_dev
    environment:
      - DATABASE_URL=postgresql://sv:sv@db:5432/sv
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./api:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: sv_web_dev
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      - VITE_API_BASE_URL=http://localhost:8000

volumes:
  postgres_data:
