name: API Tests

on:
  push:
    paths:
      - 'api/**'
      - '.github/workflows/api-tests.yml'
  pull_request:
    paths:
      - 'api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt -r api/requirements-dev.txt
      - name: Run tests
        env:
          # No DB needed for unit tests in this job; health test mocks ping
          PYTHONPATH: .
        run: |
          pytest -q api/tests
